apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: operators.operators.coreos.com
  annotations:
    displayName: Operator
    description: Operator represents an operator installation.
spec:
  group: operators.coreos.com
  versions:
  - name: v2alpha1
    served: true
    storage: true
  scope: Cluster
  names:
    plural: operators
    singular: operator
    kind: Operator
    listKind: OperatorList
    shortNames:
    - op
    - ops
    categories:
    - olm
  subresources:
    # status enables the status subresource.
    status: {}
    